// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "img_conv_5x5.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic img_conv_5x5::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic img_conv_5x5::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state1 = "1";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state2 = "10";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state3 = "100";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state4 = "1000";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state5 = "10000";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state6 = "100000";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> img_conv_5x5::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_3 = "11";
const sc_lv<32> img_conv_5x5::ap_const_lv32_5 = "101";
const sc_lv<32> img_conv_5x5::ap_const_lv32_1 = "1";
const sc_lv<32> img_conv_5x5::ap_const_lv32_2 = "10";
const sc_lv<1> img_conv_5x5::ap_const_lv1_0 = "0";
const sc_lv<32> img_conv_5x5::ap_const_lv32_4 = "100";
const sc_lv<32> img_conv_5x5::ap_const_lv32_6 = "110";
const sc_lv<32> img_conv_5x5::ap_const_lv32_7 = "111";
const sc_lv<6> img_conv_5x5::ap_const_lv6_0 = "000000";
const sc_lv<1> img_conv_5x5::ap_const_lv1_1 = "1";
const sc_lv<21> img_conv_5x5::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<3> img_conv_5x5::ap_const_lv3_0 = "000";
const sc_lv<6> img_conv_5x5::ap_const_lv6_3C = "111100";
const sc_lv<6> img_conv_5x5::ap_const_lv6_1 = "1";
const sc_lv<3> img_conv_5x5::ap_const_lv3_5 = "101";
const sc_lv<3> img_conv_5x5::ap_const_lv3_1 = "1";
const sc_lv<32> img_conv_5x5::ap_const_lv32_14 = "10100";
const sc_lv<32> img_conv_5x5::ap_const_lv32_8 = "1000";
const sc_lv<13> img_conv_5x5::ap_const_lv13_0 = "0000000000000";
const sc_lv<8> img_conv_5x5::ap_const_lv8_FF = "11111111";
const sc_lv<4> img_conv_5x5::ap_const_lv4_8 = "1000";
const sc_lv<5> img_conv_5x5::ap_const_lv5_10 = "10000";
const sc_lv<4> img_conv_5x5::ap_const_lv4_5 = "101";
const sc_lv<4> img_conv_5x5::ap_const_lv4_A = "1010";
const sc_lv<6> img_conv_5x5::ap_const_lv6_20 = "100000";
const sc_lv<5> img_conv_5x5::ap_const_lv5_F = "1111";
const sc_lv<5> img_conv_5x5::ap_const_lv5_14 = "10100";
const bool img_conv_5x5::ap_const_boolean_1 = true;

img_conv_5x5::img_conv_5x5(sc_module_name name) : sc_module(name), mVcdFile(0) {
    convolve_mac_mulabkb_U1 = new convolve_mac_mulabkb<1,1,8,8,16,17>("convolve_mac_mulabkb_U1");
    convolve_mac_mulabkb_U1->din0(grp_fu_550_p0);
    convolve_mac_mulabkb_U1->din1(mask_load_1_reg_680);
    convolve_mac_mulabkb_U1->din2(sum00_fu_478_p2);
    convolve_mac_mulabkb_U1->dout(grp_fu_550_p3);
    convolve_mac_mulacud_U2 = new convolve_mac_mulacud<1,1,8,8,17,18>("convolve_mac_mulacud_U2");
    convolve_mac_mulacud_U2->din0(grp_fu_558_p0);
    convolve_mac_mulacud_U2->din1(mask_load_2_reg_685);
    convolve_mac_mulacud_U2->din2(grp_fu_566_p3);
    convolve_mac_mulacud_U2->dout(grp_fu_558_p3);
    convolve_mac_mulabkb_U3 = new convolve_mac_mulabkb<1,1,8,8,16,17>("convolve_mac_mulabkb_U3");
    convolve_mac_mulabkb_U3->din0(grp_fu_566_p0);
    convolve_mac_mulabkb_U3->din1(reg_224);
    convolve_mac_mulabkb_U3->din2(sum33_reg_700);
    convolve_mac_mulabkb_U3->dout(grp_fu_566_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_IN4_0_rec_cast1_fu_228_p1);
    sensitive << ( IN4_0_rec_reg_184 );

    SC_METHOD(thread_IN4_0_rec_cast_fu_232_p1);
    sensitive << ( IN4_0_rec_reg_184 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_237_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_237_p2 );

    SC_METHOD(thread_exitcond2_fu_237_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( IN4_0_rec_reg_184 );

    SC_METHOD(thread_exitcond_fu_257_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_grp_fu_550_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_550_p00 );

    SC_METHOD(thread_grp_fu_550_p00);
    sensitive << ( inptr_load_1_reg_660 );

    SC_METHOD(thread_grp_fu_558_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_558_p00 );

    SC_METHOD(thread_grp_fu_558_p00);
    sensitive << ( inptr_load_2_reg_665 );

    SC_METHOD(thread_grp_fu_566_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_566_p00 );

    SC_METHOD(thread_grp_fu_566_p00);
    sensitive << ( reg_220 );

    SC_METHOD(thread_i_1_fu_263_p2);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_i_cast1_fu_249_p1);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_i_cast_fu_253_p1);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_icmp_fu_319_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_257_p2 );
    sensitive << ( tmp_3_fu_309_p4 );

    SC_METHOD(thread_inptr_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sum1_cast_fu_288_p1 );
    sensitive << ( sum3_cast_fu_363_p1 );
    sensitive << ( sum9_cast_fu_445_p1 );

    SC_METHOD(thread_inptr_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sum5_cast_fu_386_p1 );
    sensitive << ( sum7_cast_fu_423_p1 );

    SC_METHOD(thread_inptr_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_inptr_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mask_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_6_fu_269_p1 );
    sensitive << ( tmp_8_fu_396_p1 );
    sensitive << ( tmp_12_fu_465_p1 );

    SC_METHOD(thread_mask_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_s_fu_406_p1 );
    sensitive << ( tmp_10_fu_455_p1 );

    SC_METHOD(thread_mask_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mask_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_outptr_address0);
    sensitive << ( outptr_addr_reg_586 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_outptr_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_outptr_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_fu_319_p2 );
    sensitive << ( tmp_4_fu_325_p1 );

    SC_METHOD(thread_outptr_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_257_p2 );

    SC_METHOD(thread_p_cast_fu_540_p1);
    sensitive << ( tmp_13_fu_534_p2 );

    SC_METHOD(thread_p_rec_fu_243_p2);
    sensitive << ( IN4_0_rec_reg_184 );

    SC_METHOD(thread_p_s_fu_301_p3);
    sensitive << ( sum_reg_196 );
    sensitive << ( tmp_2_fu_293_p3 );

    SC_METHOD(thread_sum00_fu_478_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum00_fu_478_p00 );

    SC_METHOD(thread_sum00_fu_478_p00);
    sensitive << ( reg_220 );

    SC_METHOD(thread_sum00_fu_478_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( reg_224 );

    SC_METHOD(thread_sum00_fu_478_p2);
    sensitive << ( sum00_fu_478_p0 );
    sensitive << ( sum00_fu_478_p1 );

    SC_METHOD(thread_sum1_cast_fu_288_p1);
    sensitive << ( sum1_fu_283_p2 );

    SC_METHOD(thread_sum1_fu_283_p2);
    sensitive << ( IN4_0_rec_cast1_reg_581 );
    sensitive << ( tmp3_fu_274_p4 );

    SC_METHOD(thread_sum33_fu_502_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum33_fu_502_p00 );

    SC_METHOD(thread_sum33_fu_502_p00);
    sensitive << ( inptr_q1 );

    SC_METHOD(thread_sum33_fu_502_p1);
    sensitive << ( mask_q1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_sum33_fu_502_p2);
    sensitive << ( sum33_fu_502_p0 );
    sensitive << ( sum33_fu_502_p1 );

    SC_METHOD(thread_sum3_cast_fu_363_p1);
    sensitive << ( sum3_fu_357_p2 );

    SC_METHOD(thread_sum3_fu_357_p2);
    sensitive << ( tmp4_fu_338_p3 );
    sensitive << ( tmp5_cast_fu_353_p1 );

    SC_METHOD(thread_sum5_cast_fu_386_p1);
    sensitive << ( sum5_fu_380_p2 );

    SC_METHOD(thread_sum5_fu_380_p2);
    sensitive << ( tmp4_fu_338_p3 );
    sensitive << ( tmp7_cast_fu_376_p1 );

    SC_METHOD(thread_sum7_cast_fu_423_p1);
    sensitive << ( sum7_fu_418_p2 );

    SC_METHOD(thread_sum7_fu_418_p2);
    sensitive << ( tmp4_reg_629 );
    sensitive << ( tmp9_cast_fu_414_p1 );

    SC_METHOD(thread_sum9_cast_fu_445_p1);
    sensitive << ( sum9_fu_440_p2 );

    SC_METHOD(thread_sum9_fu_440_p2);
    sensitive << ( tmp4_reg_629 );
    sensitive << ( tmp11_cast_fu_436_p1 );

    SC_METHOD(thread_sum_1_fu_544_p2);
    sensitive << ( sum_reg_196 );
    sensitive << ( p_cast_fu_540_p1 );

    SC_METHOD(thread_tmp11_cast_fu_436_p1);
    sensitive << ( tmp7_fu_428_p3 );

    SC_METHOD(thread_tmp12_cast_fu_528_p1);
    sensitive << ( tmp9_reg_705 );

    SC_METHOD(thread_tmp13_cast_fu_531_p1);
    sensitive << ( tmp5_reg_710 );

    SC_METHOD(thread_tmp1_fu_368_p3);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_tmp3_fu_274_p4);
    sensitive << ( y );
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_tmp4_fu_338_p3);
    sensitive << ( y );
    sensitive << ( IN4_0_rec_reg_184 );

    SC_METHOD(thread_tmp5_cast_fu_353_p1);
    sensitive << ( tmp_fu_345_p3 );

    SC_METHOD(thread_tmp7_cast_fu_376_p1);
    sensitive << ( tmp1_fu_368_p3 );

    SC_METHOD(thread_tmp7_fu_428_p3);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_tmp9_cast1_fu_411_p1);
    sensitive << ( tmp_reg_635 );

    SC_METHOD(thread_tmp9_cast_fu_414_p1);
    sensitive << ( tmp9_cast1_fu_411_p1 );

    SC_METHOD(thread_tmp_10_fu_455_p1);
    sensitive << ( tmp_1_fu_450_p2 );

    SC_METHOD(thread_tmp_11_fu_460_p2);
    sensitive << ( i_cast1_reg_599 );

    SC_METHOD(thread_tmp_12_fu_465_p1);
    sensitive << ( tmp_11_fu_460_p2 );

    SC_METHOD(thread_tmp_13_fu_534_p2);
    sensitive << ( tmp13_cast_fu_531_p1 );
    sensitive << ( tmp12_cast_fu_528_p1 );

    SC_METHOD(thread_tmp_1_fu_450_p2);
    sensitive << ( i_cast1_reg_599 );

    SC_METHOD(thread_tmp_2_fu_293_p3);
    sensitive << ( sum_reg_196 );

    SC_METHOD(thread_tmp_3_fu_309_p4);
    sensitive << ( p_s_fu_301_p3 );

    SC_METHOD(thread_tmp_4_fu_325_p1);
    sensitive << ( p_s_fu_301_p3 );

    SC_METHOD(thread_tmp_6_fu_269_p1);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_tmp_7_fu_391_p2);
    sensitive << ( i_cast_reg_605 );

    SC_METHOD(thread_tmp_8_fu_396_p1);
    sensitive << ( tmp_7_fu_391_p2 );

    SC_METHOD(thread_tmp_9_fu_401_p2);
    sensitive << ( i_cast_reg_605 );

    SC_METHOD(thread_tmp_fu_345_p3);
    sensitive << ( i_reg_208 );

    SC_METHOD(thread_tmp_s_fu_406_p1);
    sensitive << ( tmp_9_fu_401_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_257_p2 );
    sensitive << ( exitcond2_fu_237_p2 );

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "img_conv_5x5_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inptr_address0, "(port)inptr_address0");
    sc_trace(mVcdFile, inptr_ce0, "(port)inptr_ce0");
    sc_trace(mVcdFile, inptr_q0, "(port)inptr_q0");
    sc_trace(mVcdFile, inptr_address1, "(port)inptr_address1");
    sc_trace(mVcdFile, inptr_ce1, "(port)inptr_ce1");
    sc_trace(mVcdFile, inptr_q1, "(port)inptr_q1");
    sc_trace(mVcdFile, outptr_address0, "(port)outptr_address0");
    sc_trace(mVcdFile, outptr_ce0, "(port)outptr_ce0");
    sc_trace(mVcdFile, outptr_we0, "(port)outptr_we0");
    sc_trace(mVcdFile, outptr_d0, "(port)outptr_d0");
    sc_trace(mVcdFile, mask_address0, "(port)mask_address0");
    sc_trace(mVcdFile, mask_ce0, "(port)mask_ce0");
    sc_trace(mVcdFile, mask_q0, "(port)mask_q0");
    sc_trace(mVcdFile, mask_address1, "(port)mask_address1");
    sc_trace(mVcdFile, mask_ce1, "(port)mask_ce1");
    sc_trace(mVcdFile, mask_q1, "(port)mask_q1");
    sc_trace(mVcdFile, y, "(port)y");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_220, "reg_220");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, reg_224, "reg_224");
    sc_trace(mVcdFile, IN4_0_rec_cast1_fu_228_p1, "IN4_0_rec_cast1_fu_228_p1");
    sc_trace(mVcdFile, IN4_0_rec_cast1_reg_581, "IN4_0_rec_cast1_reg_581");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, outptr_addr_reg_586, "outptr_addr_reg_586");
    sc_trace(mVcdFile, p_rec_fu_243_p2, "p_rec_fu_243_p2");
    sc_trace(mVcdFile, p_rec_reg_594, "p_rec_reg_594");
    sc_trace(mVcdFile, i_cast1_fu_249_p1, "i_cast1_fu_249_p1");
    sc_trace(mVcdFile, i_cast1_reg_599, "i_cast1_reg_599");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_cast_fu_253_p1, "i_cast_fu_253_p1");
    sc_trace(mVcdFile, i_cast_reg_605, "i_cast_reg_605");
    sc_trace(mVcdFile, i_1_fu_263_p2, "i_1_fu_263_p2");
    sc_trace(mVcdFile, i_1_reg_614, "i_1_reg_614");
    sc_trace(mVcdFile, exitcond_fu_257_p2, "exitcond_fu_257_p2");
    sc_trace(mVcdFile, tmp4_fu_338_p3, "tmp4_fu_338_p3");
    sc_trace(mVcdFile, tmp4_reg_629, "tmp4_reg_629");
    sc_trace(mVcdFile, tmp_fu_345_p3, "tmp_fu_345_p3");
    sc_trace(mVcdFile, tmp_reg_635, "tmp_reg_635");
    sc_trace(mVcdFile, inptr_load_1_reg_660, "inptr_load_1_reg_660");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, inptr_load_2_reg_665, "inptr_load_2_reg_665");
    sc_trace(mVcdFile, mask_load_1_reg_680, "mask_load_1_reg_680");
    sc_trace(mVcdFile, mask_load_2_reg_685, "mask_load_2_reg_685");
    sc_trace(mVcdFile, sum33_fu_502_p2, "sum33_fu_502_p2");
    sc_trace(mVcdFile, sum33_reg_700, "sum33_reg_700");
    sc_trace(mVcdFile, grp_fu_550_p3, "grp_fu_550_p3");
    sc_trace(mVcdFile, tmp9_reg_705, "tmp9_reg_705");
    sc_trace(mVcdFile, grp_fu_558_p3, "grp_fu_558_p3");
    sc_trace(mVcdFile, tmp5_reg_710, "tmp5_reg_710");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sum_1_fu_544_p2, "sum_1_fu_544_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, IN4_0_rec_reg_184, "IN4_0_rec_reg_184");
    sc_trace(mVcdFile, sum_reg_196, "sum_reg_196");
    sc_trace(mVcdFile, exitcond2_fu_237_p2, "exitcond2_fu_237_p2");
    sc_trace(mVcdFile, i_reg_208, "i_reg_208");
    sc_trace(mVcdFile, IN4_0_rec_cast_fu_232_p1, "IN4_0_rec_cast_fu_232_p1");
    sc_trace(mVcdFile, sum1_cast_fu_288_p1, "sum1_cast_fu_288_p1");
    sc_trace(mVcdFile, tmp_6_fu_269_p1, "tmp_6_fu_269_p1");
    sc_trace(mVcdFile, sum3_cast_fu_363_p1, "sum3_cast_fu_363_p1");
    sc_trace(mVcdFile, sum5_cast_fu_386_p1, "sum5_cast_fu_386_p1");
    sc_trace(mVcdFile, tmp_8_fu_396_p1, "tmp_8_fu_396_p1");
    sc_trace(mVcdFile, tmp_s_fu_406_p1, "tmp_s_fu_406_p1");
    sc_trace(mVcdFile, sum7_cast_fu_423_p1, "sum7_cast_fu_423_p1");
    sc_trace(mVcdFile, sum9_cast_fu_445_p1, "sum9_cast_fu_445_p1");
    sc_trace(mVcdFile, tmp_10_fu_455_p1, "tmp_10_fu_455_p1");
    sc_trace(mVcdFile, tmp_12_fu_465_p1, "tmp_12_fu_465_p1");
    sc_trace(mVcdFile, tmp3_fu_274_p4, "tmp3_fu_274_p4");
    sc_trace(mVcdFile, sum1_fu_283_p2, "sum1_fu_283_p2");
    sc_trace(mVcdFile, tmp_2_fu_293_p3, "tmp_2_fu_293_p3");
    sc_trace(mVcdFile, p_s_fu_301_p3, "p_s_fu_301_p3");
    sc_trace(mVcdFile, tmp_3_fu_309_p4, "tmp_3_fu_309_p4");
    sc_trace(mVcdFile, icmp_fu_319_p2, "icmp_fu_319_p2");
    sc_trace(mVcdFile, tmp_4_fu_325_p1, "tmp_4_fu_325_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_353_p1, "tmp5_cast_fu_353_p1");
    sc_trace(mVcdFile, sum3_fu_357_p2, "sum3_fu_357_p2");
    sc_trace(mVcdFile, tmp1_fu_368_p3, "tmp1_fu_368_p3");
    sc_trace(mVcdFile, tmp7_cast_fu_376_p1, "tmp7_cast_fu_376_p1");
    sc_trace(mVcdFile, sum5_fu_380_p2, "sum5_fu_380_p2");
    sc_trace(mVcdFile, tmp_7_fu_391_p2, "tmp_7_fu_391_p2");
    sc_trace(mVcdFile, tmp_9_fu_401_p2, "tmp_9_fu_401_p2");
    sc_trace(mVcdFile, tmp9_cast1_fu_411_p1, "tmp9_cast1_fu_411_p1");
    sc_trace(mVcdFile, tmp9_cast_fu_414_p1, "tmp9_cast_fu_414_p1");
    sc_trace(mVcdFile, sum7_fu_418_p2, "sum7_fu_418_p2");
    sc_trace(mVcdFile, tmp7_fu_428_p3, "tmp7_fu_428_p3");
    sc_trace(mVcdFile, tmp11_cast_fu_436_p1, "tmp11_cast_fu_436_p1");
    sc_trace(mVcdFile, sum9_fu_440_p2, "sum9_fu_440_p2");
    sc_trace(mVcdFile, tmp_1_fu_450_p2, "tmp_1_fu_450_p2");
    sc_trace(mVcdFile, tmp_11_fu_460_p2, "tmp_11_fu_460_p2");
    sc_trace(mVcdFile, sum00_fu_478_p0, "sum00_fu_478_p0");
    sc_trace(mVcdFile, sum00_fu_478_p1, "sum00_fu_478_p1");
    sc_trace(mVcdFile, sum00_fu_478_p2, "sum00_fu_478_p2");
    sc_trace(mVcdFile, sum33_fu_502_p0, "sum33_fu_502_p0");
    sc_trace(mVcdFile, sum33_fu_502_p1, "sum33_fu_502_p1");
    sc_trace(mVcdFile, grp_fu_566_p3, "grp_fu_566_p3");
    sc_trace(mVcdFile, tmp13_cast_fu_531_p1, "tmp13_cast_fu_531_p1");
    sc_trace(mVcdFile, tmp12_cast_fu_528_p1, "tmp12_cast_fu_528_p1");
    sc_trace(mVcdFile, tmp_13_fu_534_p2, "tmp_13_fu_534_p2");
    sc_trace(mVcdFile, p_cast_fu_540_p1, "p_cast_fu_540_p1");
    sc_trace(mVcdFile, grp_fu_550_p0, "grp_fu_550_p0");
    sc_trace(mVcdFile, grp_fu_558_p0, "grp_fu_558_p0");
    sc_trace(mVcdFile, grp_fu_566_p0, "grp_fu_566_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_550_p00, "grp_fu_550_p00");
    sc_trace(mVcdFile, grp_fu_558_p00, "grp_fu_558_p00");
    sc_trace(mVcdFile, grp_fu_566_p00, "grp_fu_566_p00");
    sc_trace(mVcdFile, sum00_fu_478_p00, "sum00_fu_478_p00");
    sc_trace(mVcdFile, sum33_fu_502_p00, "sum33_fu_502_p00");
#endif

    }
}

img_conv_5x5::~img_conv_5x5() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete convolve_mac_mulabkb_U1;
    delete convolve_mac_mulacud_U2;
    delete convolve_mac_mulabkb_U3;
}

void img_conv_5x5::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_257_p2.read(), ap_const_lv1_1))) {
        IN4_0_rec_reg_184 = p_rec_reg_594.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        IN4_0_rec_reg_184 = ap_const_lv6_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_237_p2.read()))) {
        i_reg_208 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_reg_208 = i_1_reg_614.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_237_p2.read()))) {
        sum_reg_196 = ap_const_lv21_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sum_reg_196 = sum_1_fu_544_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IN4_0_rec_cast1_reg_581 = IN4_0_rec_cast1_fu_228_p1.read();
        outptr_addr_reg_586 =  (sc_lv<6>) (IN4_0_rec_cast_fu_232_p1.read());
        p_rec_reg_594 = p_rec_fu_243_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_reg_614 = i_1_fu_263_p2.read();
        i_cast1_reg_599 = i_cast1_fu_249_p1.read();
        i_cast_reg_605 = i_cast_fu_253_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_load_1_reg_660 = inptr_q0.read();
        inptr_load_2_reg_665 = inptr_q1.read();
        mask_load_1_reg_680 = mask_q0.read();
        mask_load_2_reg_685 = mask_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        reg_220 = inptr_q0.read();
        reg_224 = mask_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sum33_reg_700 = sum33_fu_502_p2.read();
        tmp9_reg_705 = grp_fu_550_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp4_reg_629 = tmp4_fu_338_p3.read();
        tmp_reg_635 = tmp_fu_345_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp5_reg_710 = grp_fu_558_p3.read();
    }
}

void img_conv_5x5::thread_IN4_0_rec_cast1_fu_228_p1() {
    IN4_0_rec_cast1_fu_228_p1 = esl_zext<11,6>(IN4_0_rec_reg_184.read());
}

void img_conv_5x5::thread_IN4_0_rec_cast_fu_232_p1() {
    IN4_0_rec_cast_fu_232_p1 = esl_zext<64,6>(IN4_0_rec_reg_184.read());
}

void img_conv_5x5::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void img_conv_5x5::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void img_conv_5x5::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void img_conv_5x5::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void img_conv_5x5::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void img_conv_5x5::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void img_conv_5x5::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void img_conv_5x5::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void img_conv_5x5::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_237_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_237_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_exitcond2_fu_237_p2() {
    exitcond2_fu_237_p2 = (!IN4_0_rec_reg_184.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(IN4_0_rec_reg_184.read() == ap_const_lv6_3C);
}

void img_conv_5x5::thread_exitcond_fu_257_p2() {
    exitcond_fu_257_p2 = (!i_reg_208.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_208.read() == ap_const_lv3_5);
}

void img_conv_5x5::thread_grp_fu_550_p0() {
    grp_fu_550_p0 =  (sc_lv<8>) (grp_fu_550_p00.read());
}

void img_conv_5x5::thread_grp_fu_550_p00() {
    grp_fu_550_p00 = esl_zext<16,8>(inptr_load_1_reg_660.read());
}

void img_conv_5x5::thread_grp_fu_558_p0() {
    grp_fu_558_p0 =  (sc_lv<8>) (grp_fu_558_p00.read());
}

void img_conv_5x5::thread_grp_fu_558_p00() {
    grp_fu_558_p00 = esl_zext<16,8>(inptr_load_2_reg_665.read());
}

void img_conv_5x5::thread_grp_fu_566_p0() {
    grp_fu_566_p0 =  (sc_lv<8>) (grp_fu_566_p00.read());
}

void img_conv_5x5::thread_grp_fu_566_p00() {
    grp_fu_566_p00 = esl_zext<16,8>(reg_220.read());
}

void img_conv_5x5::thread_i_1_fu_263_p2() {
    i_1_fu_263_p2 = (!i_reg_208.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_208.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void img_conv_5x5::thread_i_cast1_fu_249_p1() {
    i_cast1_fu_249_p1 = esl_zext<5,3>(i_reg_208.read());
}

void img_conv_5x5::thread_i_cast_fu_253_p1() {
    i_cast_fu_253_p1 = esl_zext<4,3>(i_reg_208.read());
}

void img_conv_5x5::thread_icmp_fu_319_p2() {
    icmp_fu_319_p2 = (!tmp_3_fu_309_p4.read().is_01() || !ap_const_lv13_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_309_p4.read() != ap_const_lv13_0);
}

void img_conv_5x5::thread_inptr_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_address0 =  (sc_lv<11>) (sum9_cast_fu_445_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        inptr_address0 =  (sc_lv<11>) (sum3_cast_fu_363_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        inptr_address0 =  (sc_lv<11>) (sum1_cast_fu_288_p1.read());
    } else {
        inptr_address0 = "XXXXXXXXXXX";
    }
}

void img_conv_5x5::thread_inptr_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_address1 =  (sc_lv<11>) (sum7_cast_fu_423_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        inptr_address1 =  (sc_lv<11>) (sum5_cast_fu_386_p1.read());
    } else {
        inptr_address1 = "XXXXXXXXXXX";
    }
}

void img_conv_5x5::thread_inptr_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        inptr_ce0 = ap_const_logic_1;
    } else {
        inptr_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_inptr_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        inptr_ce1 = ap_const_logic_1;
    } else {
        inptr_ce1 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_mask_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_12_fu_465_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_8_fu_396_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_6_fu_269_p1.read());
    } else {
        mask_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void img_conv_5x5::thread_mask_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mask_address1 =  (sc_lv<5>) (tmp_10_fu_455_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mask_address1 =  (sc_lv<5>) (tmp_s_fu_406_p1.read());
    } else {
        mask_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void img_conv_5x5::thread_mask_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mask_ce0 = ap_const_logic_1;
    } else {
        mask_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_mask_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mask_ce1 = ap_const_logic_1;
    } else {
        mask_ce1 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_outptr_address0() {
    outptr_address0 = outptr_addr_reg_586.read();
}

void img_conv_5x5::thread_outptr_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        outptr_ce0 = ap_const_logic_1;
    } else {
        outptr_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_outptr_d0() {
    outptr_d0 = (!icmp_fu_319_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_fu_319_p2.read()[0].to_bool())? ap_const_lv8_FF: tmp_4_fu_325_p1.read());
}

void img_conv_5x5::thread_outptr_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_257_p2.read(), ap_const_lv1_1))) {
        outptr_we0 = ap_const_logic_1;
    } else {
        outptr_we0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_p_cast_fu_540_p1() {
    p_cast_fu_540_p1 = esl_sext<21,19>(tmp_13_fu_534_p2.read());
}

void img_conv_5x5::thread_p_rec_fu_243_p2() {
    p_rec_fu_243_p2 = (!IN4_0_rec_reg_184.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(IN4_0_rec_reg_184.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void img_conv_5x5::thread_p_s_fu_301_p3() {
    p_s_fu_301_p3 = (!tmp_2_fu_293_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_2_fu_293_p3.read()[0].to_bool())? ap_const_lv21_0: sum_reg_196.read());
}

void img_conv_5x5::thread_sum00_fu_478_p0() {
    sum00_fu_478_p0 =  (sc_lv<8>) (sum00_fu_478_p00.read());
}

void img_conv_5x5::thread_sum00_fu_478_p00() {
    sum00_fu_478_p00 = esl_zext<16,8>(reg_220.read());
}

void img_conv_5x5::thread_sum00_fu_478_p1() {
    sum00_fu_478_p1 = reg_224.read();
}

void img_conv_5x5::thread_sum00_fu_478_p2() {
    sum00_fu_478_p2 = (!sum00_fu_478_p0.read().is_01() || !sum00_fu_478_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(sum00_fu_478_p0.read()) * sc_bigint<8>(sum00_fu_478_p1.read());
}

void img_conv_5x5::thread_sum1_cast_fu_288_p1() {
    sum1_cast_fu_288_p1 = esl_zext<64,11>(sum1_fu_283_p2.read());
}

void img_conv_5x5::thread_sum1_fu_283_p2() {
    sum1_fu_283_p2 = (!tmp3_fu_274_p4.read().is_01() || !IN4_0_rec_cast1_reg_581.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp3_fu_274_p4.read()) + sc_biguint<11>(IN4_0_rec_cast1_reg_581.read()));
}

void img_conv_5x5::thread_sum33_fu_502_p0() {
    sum33_fu_502_p0 =  (sc_lv<8>) (sum33_fu_502_p00.read());
}

void img_conv_5x5::thread_sum33_fu_502_p00() {
    sum33_fu_502_p00 = esl_zext<16,8>(inptr_q1.read());
}

void img_conv_5x5::thread_sum33_fu_502_p1() {
    sum33_fu_502_p1 = mask_q1.read();
}

void img_conv_5x5::thread_sum33_fu_502_p2() {
    sum33_fu_502_p2 = (!sum33_fu_502_p0.read().is_01() || !sum33_fu_502_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(sum33_fu_502_p0.read()) * sc_bigint<8>(sum33_fu_502_p1.read());
}

void img_conv_5x5::thread_sum3_cast_fu_363_p1() {
    sum3_cast_fu_363_p1 = esl_zext<64,11>(sum3_fu_357_p2.read());
}

void img_conv_5x5::thread_sum3_fu_357_p2() {
    sum3_fu_357_p2 = (!tmp5_cast_fu_353_p1.read().is_01() || !tmp4_fu_338_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp5_cast_fu_353_p1.read()) + sc_biguint<11>(tmp4_fu_338_p3.read()));
}

void img_conv_5x5::thread_sum5_cast_fu_386_p1() {
    sum5_cast_fu_386_p1 = esl_zext<64,11>(sum5_fu_380_p2.read());
}

void img_conv_5x5::thread_sum5_fu_380_p2() {
    sum5_fu_380_p2 = (!tmp7_cast_fu_376_p1.read().is_01() || !tmp4_fu_338_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp7_cast_fu_376_p1.read()) + sc_biguint<11>(tmp4_fu_338_p3.read()));
}

void img_conv_5x5::thread_sum7_cast_fu_423_p1() {
    sum7_cast_fu_423_p1 = esl_zext<64,11>(sum7_fu_418_p2.read());
}

void img_conv_5x5::thread_sum7_fu_418_p2() {
    sum7_fu_418_p2 = (!tmp9_cast_fu_414_p1.read().is_01() || !tmp4_reg_629.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp9_cast_fu_414_p1.read()) + sc_biguint<11>(tmp4_reg_629.read()));
}

void img_conv_5x5::thread_sum9_cast_fu_445_p1() {
    sum9_cast_fu_445_p1 = esl_zext<64,11>(sum9_fu_440_p2.read());
}

void img_conv_5x5::thread_sum9_fu_440_p2() {
    sum9_fu_440_p2 = (!tmp11_cast_fu_436_p1.read().is_01() || !tmp4_reg_629.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp11_cast_fu_436_p1.read()) + sc_biguint<11>(tmp4_reg_629.read()));
}

void img_conv_5x5::thread_sum_1_fu_544_p2() {
    sum_1_fu_544_p2 = (!sum_reg_196.read().is_01() || !p_cast_fu_540_p1.read().is_01())? sc_lv<21>(): (sc_biguint<21>(sum_reg_196.read()) + sc_bigint<21>(p_cast_fu_540_p1.read()));
}

void img_conv_5x5::thread_tmp11_cast_fu_436_p1() {
    tmp11_cast_fu_436_p1 = esl_zext<11,9>(tmp7_fu_428_p3.read());
}

void img_conv_5x5::thread_tmp12_cast_fu_528_p1() {
    tmp12_cast_fu_528_p1 = esl_sext<19,17>(tmp9_reg_705.read());
}

void img_conv_5x5::thread_tmp13_cast_fu_531_p1() {
    tmp13_cast_fu_531_p1 = esl_sext<19,18>(tmp5_reg_710.read());
}

void img_conv_5x5::thread_tmp1_fu_368_p3() {
    tmp1_fu_368_p3 = esl_concat<5,3>(ap_const_lv5_10, i_reg_208.read());
}

void img_conv_5x5::thread_tmp3_fu_274_p4() {
    tmp3_fu_274_p4 = esl_concat<8,3>(esl_concat<5,3>(y.read(), ap_const_lv3_0), i_reg_208.read());
}

void img_conv_5x5::thread_tmp4_fu_338_p3() {
    tmp4_fu_338_p3 = esl_concat<5,6>(y.read(), IN4_0_rec_reg_184.read());
}

void img_conv_5x5::thread_tmp5_cast_fu_353_p1() {
    tmp5_cast_fu_353_p1 = esl_zext<11,7>(tmp_fu_345_p3.read());
}

void img_conv_5x5::thread_tmp7_cast_fu_376_p1() {
    tmp7_cast_fu_376_p1 = esl_zext<11,8>(tmp1_fu_368_p3.read());
}

void img_conv_5x5::thread_tmp7_fu_428_p3() {
    tmp7_fu_428_p3 = esl_concat<6,3>(ap_const_lv6_20, i_reg_208.read());
}

void img_conv_5x5::thread_tmp9_cast1_fu_411_p1() {
    tmp9_cast1_fu_411_p1 = esl_sext<8,7>(tmp_reg_635.read());
}

void img_conv_5x5::thread_tmp9_cast_fu_414_p1() {
    tmp9_cast_fu_414_p1 = esl_zext<11,8>(tmp9_cast1_fu_411_p1.read());
}

void img_conv_5x5::thread_tmp_10_fu_455_p1() {
    tmp_10_fu_455_p1 = esl_zext<64,5>(tmp_1_fu_450_p2.read());
}

void img_conv_5x5::thread_tmp_11_fu_460_p2() {
    tmp_11_fu_460_p2 = (!i_cast1_reg_599.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<5>(): (sc_biguint<5>(i_cast1_reg_599.read()) + sc_bigint<5>(ap_const_lv5_14));
}

void img_conv_5x5::thread_tmp_12_fu_465_p1() {
    tmp_12_fu_465_p1 = esl_zext<64,5>(tmp_11_fu_460_p2.read());
}

void img_conv_5x5::thread_tmp_13_fu_534_p2() {
    tmp_13_fu_534_p2 = (!tmp13_cast_fu_531_p1.read().is_01() || !tmp12_cast_fu_528_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(tmp13_cast_fu_531_p1.read()) + sc_bigint<19>(tmp12_cast_fu_528_p1.read()));
}

void img_conv_5x5::thread_tmp_1_fu_450_p2() {
    tmp_1_fu_450_p2 = (!i_cast1_reg_599.read().is_01() || !ap_const_lv5_F.is_01())? sc_lv<5>(): (sc_biguint<5>(i_cast1_reg_599.read()) + sc_biguint<5>(ap_const_lv5_F));
}

void img_conv_5x5::thread_tmp_2_fu_293_p3() {
    tmp_2_fu_293_p3 = sum_reg_196.read().range(20, 20);
}

void img_conv_5x5::thread_tmp_3_fu_309_p4() {
    tmp_3_fu_309_p4 = p_s_fu_301_p3.read().range(20, 8);
}

void img_conv_5x5::thread_tmp_4_fu_325_p1() {
    tmp_4_fu_325_p1 = p_s_fu_301_p3.read().range(8-1, 0);
}

void img_conv_5x5::thread_tmp_6_fu_269_p1() {
    tmp_6_fu_269_p1 = esl_zext<64,3>(i_reg_208.read());
}

void img_conv_5x5::thread_tmp_7_fu_391_p2() {
    tmp_7_fu_391_p2 = (!i_cast_reg_605.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<4>(): (sc_biguint<4>(i_cast_reg_605.read()) + sc_biguint<4>(ap_const_lv4_5));
}

void img_conv_5x5::thread_tmp_8_fu_396_p1() {
    tmp_8_fu_396_p1 = esl_zext<64,4>(tmp_7_fu_391_p2.read());
}

void img_conv_5x5::thread_tmp_9_fu_401_p2() {
    tmp_9_fu_401_p2 = (!i_cast_reg_605.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<4>(): (sc_biguint<4>(i_cast_reg_605.read()) + sc_bigint<4>(ap_const_lv4_A));
}

void img_conv_5x5::thread_tmp_fu_345_p3() {
    tmp_fu_345_p3 = esl_concat<4,3>(ap_const_lv4_8, i_reg_208.read());
}

void img_conv_5x5::thread_tmp_s_fu_406_p1() {
    tmp_s_fu_406_p1 = esl_zext<64,4>(tmp_9_fu_401_p2.read());
}

void img_conv_5x5::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_237_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_257_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

