// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "img_conv_5x5.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic img_conv_5x5::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic img_conv_5x5::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state1 = "1";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state2 = "10";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state3 = "100";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state4 = "1000";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state5 = "10000";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state6 = "100000";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> img_conv_5x5::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_3 = "11";
const sc_lv<32> img_conv_5x5::ap_const_lv32_5 = "101";
const sc_lv<32> img_conv_5x5::ap_const_lv32_1 = "1";
const sc_lv<32> img_conv_5x5::ap_const_lv32_2 = "10";
const sc_lv<1> img_conv_5x5::ap_const_lv1_0 = "0";
const sc_lv<1> img_conv_5x5::ap_const_lv1_1 = "1";
const sc_lv<32> img_conv_5x5::ap_const_lv32_4 = "100";
const sc_lv<32> img_conv_5x5::ap_const_lv32_6 = "110";
const sc_lv<32> img_conv_5x5::ap_const_lv32_7 = "111";
const sc_lv<6> img_conv_5x5::ap_const_lv6_0 = "000000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_8 = "1000";
const sc_lv<21> img_conv_5x5::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<3> img_conv_5x5::ap_const_lv3_0 = "000";
const sc_lv<6> img_conv_5x5::ap_const_lv6_3B = "111011";
const sc_lv<6> img_conv_5x5::ap_const_lv6_1 = "1";
const sc_lv<3> img_conv_5x5::ap_const_lv3_5 = "101";
const sc_lv<3> img_conv_5x5::ap_const_lv3_1 = "1";
const sc_lv<4> img_conv_5x5::ap_const_lv4_8 = "1000";
const sc_lv<5> img_conv_5x5::ap_const_lv5_10 = "10000";
const sc_lv<6> img_conv_5x5::ap_const_lv6_20 = "100000";
const sc_lv<32> img_conv_5x5::ap_const_lv32_14 = "10100";
const sc_lv<13> img_conv_5x5::ap_const_lv13_0 = "0000000000000";
const sc_lv<4> img_conv_5x5::ap_const_lv4_5 = "101";
const sc_lv<4> img_conv_5x5::ap_const_lv4_A = "1010";
const sc_lv<5> img_conv_5x5::ap_const_lv5_F = "1111";
const sc_lv<5> img_conv_5x5::ap_const_lv5_14 = "10100";
const sc_lv<8> img_conv_5x5::ap_const_lv8_FF = "11111111";
const bool img_conv_5x5::ap_const_boolean_1 = true;

img_conv_5x5::img_conv_5x5(sc_module_name name) : sc_module(name), mVcdFile(0) {
    img_conv_5x5_mac_bkb_U1 = new img_conv_5x5_mac_bkb<1,1,8,8,16,17>("img_conv_5x5_mac_bkb_U1");
    img_conv_5x5_mac_bkb_U1->din0(grp_fu_533_p0);
    img_conv_5x5_mac_bkb_U1->din1(mask_load_1_reg_687);
    img_conv_5x5_mac_bkb_U1->din2(sum00_fu_454_p2);
    img_conv_5x5_mac_bkb_U1->dout(grp_fu_533_p3);
    img_conv_5x5_mac_cud_U2 = new img_conv_5x5_mac_cud<1,1,8,8,17,18>("img_conv_5x5_mac_cud_U2");
    img_conv_5x5_mac_cud_U2->din0(grp_fu_541_p0);
    img_conv_5x5_mac_cud_U2->din1(mask_load_2_reg_692);
    img_conv_5x5_mac_cud_U2->din2(grp_fu_549_p3);
    img_conv_5x5_mac_cud_U2->dout(grp_fu_541_p3);
    img_conv_5x5_mac_bkb_U3 = new img_conv_5x5_mac_bkb<1,1,8,8,16,17>("img_conv_5x5_mac_bkb_U3");
    img_conv_5x5_mac_bkb_U3->din0(grp_fu_549_p0);
    img_conv_5x5_mac_bkb_U3->din1(reg_225);
    img_conv_5x5_mac_bkb_U3->din2(sum33_reg_707);
    img_conv_5x5_mac_bkb_U3->dout(grp_fu_549_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_IN5_0_rec_cast17_cas_fu_237_p1);
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_IN5_0_rec_cast1_fu_229_p1);
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_IN5_0_rec_cast2_fu_233_p1);
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_IN5_0_rec_cast_fu_241_p1);
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_246_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_246_p2 );

    SC_METHOD(thread_exitcond2_fu_246_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_exitcond_fu_266_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_grp_fu_533_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_533_p00 );

    SC_METHOD(thread_grp_fu_533_p00);
    sensitive << ( inptr_load_1_reg_667 );

    SC_METHOD(thread_grp_fu_541_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_541_p00 );

    SC_METHOD(thread_grp_fu_541_p00);
    sensitive << ( inptr_load_2_reg_672 );

    SC_METHOD(thread_grp_fu_549_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_549_p00 );

    SC_METHOD(thread_grp_fu_549_p00);
    sensitive << ( reg_221 );

    SC_METHOD(thread_i_1_fu_272_p2);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_i_cast1_fu_258_p1);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_i_cast_fu_262_p1);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_icmp_fu_376_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_266_p2 );
    sensitive << ( tmp_2_fu_366_p4 );

    SC_METHOD(thread_inptr_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sum1_cast_fu_293_p1 );
    sensitive << ( sum3_cast_fu_386_p1 );
    sensitive << ( sum9_cast_fu_422_p1 );

    SC_METHOD(thread_inptr_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sum5_cast_fu_390_p1 );
    sensitive << ( sum7_cast_fu_417_p1 );

    SC_METHOD(thread_inptr_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_inptr_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mask_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_4_fu_278_p1 );
    sensitive << ( tmp_6_fu_399_p1 );
    sensitive << ( tmp_11_fu_441_p1 );

    SC_METHOD(thread_mask_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_8_fu_409_p1 );
    sensitive << ( tmp_s_fu_431_p1 );

    SC_METHOD(thread_mask_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mask_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_outptr_address0);
    sensitive << ( outptr_addr_reg_578 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_outptr_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_outptr_d0);
    sensitive << ( icmp_reg_637 );
    sensitive << ( tmp_13_reg_642 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_outptr_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_p_cast_fu_516_p1);
    sensitive << ( tmp_12_fu_510_p2 );

    SC_METHOD(thread_p_rec_fu_252_p2);
    sensitive << ( IN5_0_rec_reg_186 );

    SC_METHOD(thread_p_s_fu_358_p3);
    sensitive << ( tmp_1_fu_350_p3 );
    sensitive << ( tmp_fu_346_p1 );

    SC_METHOD(thread_sum00_fu_454_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum00_fu_454_p00 );

    SC_METHOD(thread_sum00_fu_454_p00);
    sensitive << ( reg_221 );

    SC_METHOD(thread_sum00_fu_454_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( reg_225 );

    SC_METHOD(thread_sum00_fu_454_p2);
    sensitive << ( sum00_fu_454_p0 );
    sensitive << ( sum00_fu_454_p1 );

    SC_METHOD(thread_sum1_cast_fu_293_p1);
    sensitive << ( sum1_fu_287_p2 );

    SC_METHOD(thread_sum1_fu_287_p2);
    sensitive << ( IN5_0_rec_reg_186 );
    sensitive << ( tmp_4_cast_fu_283_p1 );

    SC_METHOD(thread_sum33_fu_478_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum33_fu_478_p00 );

    SC_METHOD(thread_sum33_fu_478_p00);
    sensitive << ( inptr_q1 );

    SC_METHOD(thread_sum33_fu_478_p1);
    sensitive << ( mask_q1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_sum33_fu_478_p2);
    sensitive << ( sum33_fu_478_p0 );
    sensitive << ( sum33_fu_478_p1 );

    SC_METHOD(thread_sum3_cast_fu_386_p1);
    sensitive << ( sum3_reg_616 );

    SC_METHOD(thread_sum3_fu_306_p2);
    sensitive << ( IN5_0_rec_cast17_cas_reg_573 );
    sensitive << ( tmp1_fu_298_p3 );

    SC_METHOD(thread_sum5_cast_fu_390_p1);
    sensitive << ( sum5_reg_622 );

    SC_METHOD(thread_sum5_fu_319_p2);
    sensitive << ( IN5_0_rec_cast2_reg_568 );
    sensitive << ( tmp2_fu_311_p3 );

    SC_METHOD(thread_sum7_cast1_fu_414_p1);
    sensitive << ( sum3_reg_616 );

    SC_METHOD(thread_sum7_cast_fu_417_p1);
    sensitive << ( sum7_cast1_fu_414_p1 );

    SC_METHOD(thread_sum9_cast_fu_422_p1);
    sensitive << ( sum9_reg_627 );

    SC_METHOD(thread_sum9_fu_332_p2);
    sensitive << ( IN5_0_rec_cast1_reg_563 );
    sensitive << ( tmp4_fu_324_p3 );

    SC_METHOD(thread_sum_1_fu_341_p2);
    sensitive << ( shift );
    sensitive << ( sum_cast_fu_337_p1 );

    SC_METHOD(thread_sum_2_fu_520_p2);
    sensitive << ( sum_reg_198 );
    sensitive << ( p_cast_fu_516_p1 );

    SC_METHOD(thread_sum_cast_fu_337_p1);
    sensitive << ( sum_reg_198 );

    SC_METHOD(thread_tmp1_fu_298_p3);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_tmp2_fu_311_p3);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_tmp4_fu_324_p3);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_tmp7_cast_fu_504_p1);
    sensitive << ( tmp7_reg_712 );

    SC_METHOD(thread_tmp8_cast_fu_507_p1);
    sensitive << ( tmp8_reg_717 );

    SC_METHOD(thread_tmp_10_fu_436_p2);
    sensitive << ( i_cast1_reg_591 );

    SC_METHOD(thread_tmp_11_fu_441_p1);
    sensitive << ( tmp_10_fu_436_p2 );

    SC_METHOD(thread_tmp_12_fu_510_p2);
    sensitive << ( tmp8_cast_fu_507_p1 );
    sensitive << ( tmp7_cast_fu_504_p1 );

    SC_METHOD(thread_tmp_13_fu_382_p1);
    sensitive << ( p_s_fu_358_p3 );

    SC_METHOD(thread_tmp_1_fu_350_p3);
    sensitive << ( sum_1_fu_341_p2 );

    SC_METHOD(thread_tmp_2_fu_366_p4);
    sensitive << ( p_s_fu_358_p3 );

    SC_METHOD(thread_tmp_4_cast_fu_283_p1);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_tmp_4_fu_278_p1);
    sensitive << ( i_reg_210 );

    SC_METHOD(thread_tmp_5_fu_394_p2);
    sensitive << ( i_cast_reg_597 );

    SC_METHOD(thread_tmp_6_fu_399_p1);
    sensitive << ( tmp_5_fu_394_p2 );

    SC_METHOD(thread_tmp_7_fu_404_p2);
    sensitive << ( i_cast_reg_597 );

    SC_METHOD(thread_tmp_8_fu_409_p1);
    sensitive << ( tmp_7_fu_404_p2 );

    SC_METHOD(thread_tmp_9_fu_426_p2);
    sensitive << ( i_cast1_reg_591 );

    SC_METHOD(thread_tmp_fu_346_p1);
    sensitive << ( sum_1_fu_341_p2 );

    SC_METHOD(thread_tmp_s_fu_431_p1);
    sensitive << ( tmp_9_fu_426_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_266_p2 );
    sensitive << ( exitcond2_fu_246_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "img_conv_5x5_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inptr_address0, "(port)inptr_address0");
    sc_trace(mVcdFile, inptr_ce0, "(port)inptr_ce0");
    sc_trace(mVcdFile, inptr_q0, "(port)inptr_q0");
    sc_trace(mVcdFile, inptr_address1, "(port)inptr_address1");
    sc_trace(mVcdFile, inptr_ce1, "(port)inptr_ce1");
    sc_trace(mVcdFile, inptr_q1, "(port)inptr_q1");
    sc_trace(mVcdFile, outptr_address0, "(port)outptr_address0");
    sc_trace(mVcdFile, outptr_ce0, "(port)outptr_ce0");
    sc_trace(mVcdFile, outptr_we0, "(port)outptr_we0");
    sc_trace(mVcdFile, outptr_d0, "(port)outptr_d0");
    sc_trace(mVcdFile, mask_address0, "(port)mask_address0");
    sc_trace(mVcdFile, mask_ce0, "(port)mask_ce0");
    sc_trace(mVcdFile, mask_q0, "(port)mask_q0");
    sc_trace(mVcdFile, mask_address1, "(port)mask_address1");
    sc_trace(mVcdFile, mask_ce1, "(port)mask_ce1");
    sc_trace(mVcdFile, mask_q1, "(port)mask_q1");
    sc_trace(mVcdFile, shift, "(port)shift");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_221, "reg_221");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, reg_225, "reg_225");
    sc_trace(mVcdFile, IN5_0_rec_cast1_fu_229_p1, "IN5_0_rec_cast1_fu_229_p1");
    sc_trace(mVcdFile, IN5_0_rec_cast1_reg_563, "IN5_0_rec_cast1_reg_563");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, IN5_0_rec_cast2_fu_233_p1, "IN5_0_rec_cast2_fu_233_p1");
    sc_trace(mVcdFile, IN5_0_rec_cast2_reg_568, "IN5_0_rec_cast2_reg_568");
    sc_trace(mVcdFile, IN5_0_rec_cast17_cas_fu_237_p1, "IN5_0_rec_cast17_cas_fu_237_p1");
    sc_trace(mVcdFile, IN5_0_rec_cast17_cas_reg_573, "IN5_0_rec_cast17_cas_reg_573");
    sc_trace(mVcdFile, outptr_addr_reg_578, "outptr_addr_reg_578");
    sc_trace(mVcdFile, p_rec_fu_252_p2, "p_rec_fu_252_p2");
    sc_trace(mVcdFile, p_rec_reg_586, "p_rec_reg_586");
    sc_trace(mVcdFile, i_cast1_fu_258_p1, "i_cast1_fu_258_p1");
    sc_trace(mVcdFile, i_cast1_reg_591, "i_cast1_reg_591");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_cast_fu_262_p1, "i_cast_fu_262_p1");
    sc_trace(mVcdFile, i_cast_reg_597, "i_cast_reg_597");
    sc_trace(mVcdFile, i_1_fu_272_p2, "i_1_fu_272_p2");
    sc_trace(mVcdFile, i_1_reg_606, "i_1_reg_606");
    sc_trace(mVcdFile, exitcond_fu_266_p2, "exitcond_fu_266_p2");
    sc_trace(mVcdFile, sum3_fu_306_p2, "sum3_fu_306_p2");
    sc_trace(mVcdFile, sum3_reg_616, "sum3_reg_616");
    sc_trace(mVcdFile, sum5_fu_319_p2, "sum5_fu_319_p2");
    sc_trace(mVcdFile, sum5_reg_622, "sum5_reg_622");
    sc_trace(mVcdFile, sum9_fu_332_p2, "sum9_fu_332_p2");
    sc_trace(mVcdFile, sum9_reg_627, "sum9_reg_627");
    sc_trace(mVcdFile, icmp_fu_376_p2, "icmp_fu_376_p2");
    sc_trace(mVcdFile, icmp_reg_637, "icmp_reg_637");
    sc_trace(mVcdFile, tmp_13_fu_382_p1, "tmp_13_fu_382_p1");
    sc_trace(mVcdFile, tmp_13_reg_642, "tmp_13_reg_642");
    sc_trace(mVcdFile, inptr_load_1_reg_667, "inptr_load_1_reg_667");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, inptr_load_2_reg_672, "inptr_load_2_reg_672");
    sc_trace(mVcdFile, mask_load_1_reg_687, "mask_load_1_reg_687");
    sc_trace(mVcdFile, mask_load_2_reg_692, "mask_load_2_reg_692");
    sc_trace(mVcdFile, sum33_fu_478_p2, "sum33_fu_478_p2");
    sc_trace(mVcdFile, sum33_reg_707, "sum33_reg_707");
    sc_trace(mVcdFile, grp_fu_533_p3, "grp_fu_533_p3");
    sc_trace(mVcdFile, tmp7_reg_712, "tmp7_reg_712");
    sc_trace(mVcdFile, grp_fu_541_p3, "grp_fu_541_p3");
    sc_trace(mVcdFile, tmp8_reg_717, "tmp8_reg_717");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sum_2_fu_520_p2, "sum_2_fu_520_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, IN5_0_rec_reg_186, "IN5_0_rec_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, sum_reg_198, "sum_reg_198");
    sc_trace(mVcdFile, exitcond2_fu_246_p2, "exitcond2_fu_246_p2");
    sc_trace(mVcdFile, i_reg_210, "i_reg_210");
    sc_trace(mVcdFile, IN5_0_rec_cast_fu_241_p1, "IN5_0_rec_cast_fu_241_p1");
    sc_trace(mVcdFile, sum1_cast_fu_293_p1, "sum1_cast_fu_293_p1");
    sc_trace(mVcdFile, tmp_4_fu_278_p1, "tmp_4_fu_278_p1");
    sc_trace(mVcdFile, sum3_cast_fu_386_p1, "sum3_cast_fu_386_p1");
    sc_trace(mVcdFile, sum5_cast_fu_390_p1, "sum5_cast_fu_390_p1");
    sc_trace(mVcdFile, tmp_6_fu_399_p1, "tmp_6_fu_399_p1");
    sc_trace(mVcdFile, tmp_8_fu_409_p1, "tmp_8_fu_409_p1");
    sc_trace(mVcdFile, sum7_cast_fu_417_p1, "sum7_cast_fu_417_p1");
    sc_trace(mVcdFile, sum9_cast_fu_422_p1, "sum9_cast_fu_422_p1");
    sc_trace(mVcdFile, tmp_s_fu_431_p1, "tmp_s_fu_431_p1");
    sc_trace(mVcdFile, tmp_11_fu_441_p1, "tmp_11_fu_441_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_283_p1, "tmp_4_cast_fu_283_p1");
    sc_trace(mVcdFile, sum1_fu_287_p2, "sum1_fu_287_p2");
    sc_trace(mVcdFile, tmp1_fu_298_p3, "tmp1_fu_298_p3");
    sc_trace(mVcdFile, tmp2_fu_311_p3, "tmp2_fu_311_p3");
    sc_trace(mVcdFile, tmp4_fu_324_p3, "tmp4_fu_324_p3");
    sc_trace(mVcdFile, sum_cast_fu_337_p1, "sum_cast_fu_337_p1");
    sc_trace(mVcdFile, sum_1_fu_341_p2, "sum_1_fu_341_p2");
    sc_trace(mVcdFile, tmp_1_fu_350_p3, "tmp_1_fu_350_p3");
    sc_trace(mVcdFile, tmp_fu_346_p1, "tmp_fu_346_p1");
    sc_trace(mVcdFile, p_s_fu_358_p3, "p_s_fu_358_p3");
    sc_trace(mVcdFile, tmp_2_fu_366_p4, "tmp_2_fu_366_p4");
    sc_trace(mVcdFile, tmp_5_fu_394_p2, "tmp_5_fu_394_p2");
    sc_trace(mVcdFile, tmp_7_fu_404_p2, "tmp_7_fu_404_p2");
    sc_trace(mVcdFile, sum7_cast1_fu_414_p1, "sum7_cast1_fu_414_p1");
    sc_trace(mVcdFile, tmp_9_fu_426_p2, "tmp_9_fu_426_p2");
    sc_trace(mVcdFile, tmp_10_fu_436_p2, "tmp_10_fu_436_p2");
    sc_trace(mVcdFile, sum00_fu_454_p0, "sum00_fu_454_p0");
    sc_trace(mVcdFile, sum00_fu_454_p1, "sum00_fu_454_p1");
    sc_trace(mVcdFile, sum00_fu_454_p2, "sum00_fu_454_p2");
    sc_trace(mVcdFile, sum33_fu_478_p0, "sum33_fu_478_p0");
    sc_trace(mVcdFile, sum33_fu_478_p1, "sum33_fu_478_p1");
    sc_trace(mVcdFile, grp_fu_549_p3, "grp_fu_549_p3");
    sc_trace(mVcdFile, tmp8_cast_fu_507_p1, "tmp8_cast_fu_507_p1");
    sc_trace(mVcdFile, tmp7_cast_fu_504_p1, "tmp7_cast_fu_504_p1");
    sc_trace(mVcdFile, tmp_12_fu_510_p2, "tmp_12_fu_510_p2");
    sc_trace(mVcdFile, p_cast_fu_516_p1, "p_cast_fu_516_p1");
    sc_trace(mVcdFile, grp_fu_533_p0, "grp_fu_533_p0");
    sc_trace(mVcdFile, grp_fu_541_p0, "grp_fu_541_p0");
    sc_trace(mVcdFile, grp_fu_549_p0, "grp_fu_549_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_533_p00, "grp_fu_533_p00");
    sc_trace(mVcdFile, grp_fu_541_p00, "grp_fu_541_p00");
    sc_trace(mVcdFile, grp_fu_549_p00, "grp_fu_549_p00");
    sc_trace(mVcdFile, sum00_fu_454_p00, "sum00_fu_454_p00");
    sc_trace(mVcdFile, sum33_fu_478_p00, "sum33_fu_478_p00");
#endif

    }
    mHdltvinHandle.open("img_conv_5x5.hdltvin.dat");
    mHdltvoutHandle.open("img_conv_5x5.hdltvout.dat");
}

img_conv_5x5::~img_conv_5x5() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete img_conv_5x5_mac_bkb_U1;
    delete img_conv_5x5_mac_cud_U2;
    delete img_conv_5x5_mac_bkb_U3;
}

void img_conv_5x5::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        IN5_0_rec_reg_186 = p_rec_reg_586.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        IN5_0_rec_reg_186 = ap_const_lv6_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_246_p2.read()))) {
        i_reg_210 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_reg_210 = i_1_reg_606.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_246_p2.read()))) {
        sum_reg_198 = ap_const_lv21_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sum_reg_198 = sum_2_fu_520_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IN5_0_rec_cast17_cas_reg_573 = IN5_0_rec_cast17_cas_fu_237_p1.read();
        IN5_0_rec_cast1_reg_563 = IN5_0_rec_cast1_fu_229_p1.read();
        IN5_0_rec_cast2_reg_568 = IN5_0_rec_cast2_fu_233_p1.read();
        outptr_addr_reg_578 =  (sc_lv<6>) (IN5_0_rec_cast_fu_241_p1.read());
        p_rec_reg_586 = p_rec_fu_252_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_reg_606 = i_1_fu_272_p2.read();
        i_cast1_reg_591 = i_cast1_fu_258_p1.read();
        i_cast_reg_597 = i_cast_fu_262_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_266_p2.read(), ap_const_lv1_1))) {
        icmp_reg_637 = icmp_fu_376_p2.read();
        tmp_13_reg_642 = tmp_13_fu_382_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_load_1_reg_667 = inptr_q0.read();
        inptr_load_2_reg_672 = inptr_q1.read();
        mask_load_1_reg_687 = mask_q0.read();
        mask_load_2_reg_692 = mask_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        reg_221 = inptr_q0.read();
        reg_225 = mask_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sum33_reg_707 = sum33_fu_478_p2.read();
        tmp7_reg_712 = grp_fu_533_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_266_p2.read(), ap_const_lv1_0))) {
        sum3_reg_616 = sum3_fu_306_p2.read();
        sum5_reg_622 = sum5_fu_319_p2.read();
        sum9_reg_627 = sum9_fu_332_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp8_reg_717 = grp_fu_541_p3.read();
    }
}

void img_conv_5x5::thread_IN5_0_rec_cast17_cas_fu_237_p1() {
    IN5_0_rec_cast17_cas_fu_237_p1 = esl_zext<7,6>(IN5_0_rec_reg_186.read());
}

void img_conv_5x5::thread_IN5_0_rec_cast1_fu_229_p1() {
    IN5_0_rec_cast1_fu_229_p1 = esl_zext<9,6>(IN5_0_rec_reg_186.read());
}

void img_conv_5x5::thread_IN5_0_rec_cast2_fu_233_p1() {
    IN5_0_rec_cast2_fu_233_p1 = esl_zext<8,6>(IN5_0_rec_reg_186.read());
}

void img_conv_5x5::thread_IN5_0_rec_cast_fu_241_p1() {
    IN5_0_rec_cast_fu_241_p1 = esl_zext<64,6>(IN5_0_rec_reg_186.read());
}

void img_conv_5x5::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void img_conv_5x5::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void img_conv_5x5::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void img_conv_5x5::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void img_conv_5x5::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void img_conv_5x5::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void img_conv_5x5::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void img_conv_5x5::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void img_conv_5x5::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void img_conv_5x5::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_246_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_246_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_exitcond2_fu_246_p2() {
    exitcond2_fu_246_p2 = (!IN5_0_rec_reg_186.read().is_01() || !ap_const_lv6_3B.is_01())? sc_lv<1>(): sc_lv<1>(IN5_0_rec_reg_186.read() == ap_const_lv6_3B);
}

void img_conv_5x5::thread_exitcond_fu_266_p2() {
    exitcond_fu_266_p2 = (!i_reg_210.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_210.read() == ap_const_lv3_5);
}

void img_conv_5x5::thread_grp_fu_533_p0() {
    grp_fu_533_p0 =  (sc_lv<8>) (grp_fu_533_p00.read());
}

void img_conv_5x5::thread_grp_fu_533_p00() {
    grp_fu_533_p00 = esl_zext<16,8>(inptr_load_1_reg_667.read());
}

void img_conv_5x5::thread_grp_fu_541_p0() {
    grp_fu_541_p0 =  (sc_lv<8>) (grp_fu_541_p00.read());
}

void img_conv_5x5::thread_grp_fu_541_p00() {
    grp_fu_541_p00 = esl_zext<16,8>(inptr_load_2_reg_672.read());
}

void img_conv_5x5::thread_grp_fu_549_p0() {
    grp_fu_549_p0 =  (sc_lv<8>) (grp_fu_549_p00.read());
}

void img_conv_5x5::thread_grp_fu_549_p00() {
    grp_fu_549_p00 = esl_zext<16,8>(reg_221.read());
}

void img_conv_5x5::thread_i_1_fu_272_p2() {
    i_1_fu_272_p2 = (!i_reg_210.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_210.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void img_conv_5x5::thread_i_cast1_fu_258_p1() {
    i_cast1_fu_258_p1 = esl_zext<5,3>(i_reg_210.read());
}

void img_conv_5x5::thread_i_cast_fu_262_p1() {
    i_cast_fu_262_p1 = esl_zext<4,3>(i_reg_210.read());
}

void img_conv_5x5::thread_icmp_fu_376_p2() {
    icmp_fu_376_p2 = (!tmp_2_fu_366_p4.read().is_01() || !ap_const_lv13_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_366_p4.read() != ap_const_lv13_0);
}

void img_conv_5x5::thread_inptr_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_address0 =  (sc_lv<11>) (sum9_cast_fu_422_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        inptr_address0 =  (sc_lv<11>) (sum3_cast_fu_386_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        inptr_address0 =  (sc_lv<11>) (sum1_cast_fu_293_p1.read());
    } else {
        inptr_address0 = "XXXXXXXXXXX";
    }
}

void img_conv_5x5::thread_inptr_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        inptr_address1 =  (sc_lv<11>) (sum7_cast_fu_417_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        inptr_address1 =  (sc_lv<11>) (sum5_cast_fu_390_p1.read());
    } else {
        inptr_address1 = "XXXXXXXXXXX";
    }
}

void img_conv_5x5::thread_inptr_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        inptr_ce0 = ap_const_logic_1;
    } else {
        inptr_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_inptr_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        inptr_ce1 = ap_const_logic_1;
    } else {
        inptr_ce1 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_mask_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_11_fu_441_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_6_fu_399_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mask_address0 =  (sc_lv<5>) (tmp_4_fu_278_p1.read());
    } else {
        mask_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void img_conv_5x5::thread_mask_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mask_address1 =  (sc_lv<5>) (tmp_s_fu_431_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mask_address1 =  (sc_lv<5>) (tmp_8_fu_409_p1.read());
    } else {
        mask_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void img_conv_5x5::thread_mask_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mask_ce0 = ap_const_logic_1;
    } else {
        mask_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_mask_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mask_ce1 = ap_const_logic_1;
    } else {
        mask_ce1 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_outptr_address0() {
    outptr_address0 = outptr_addr_reg_578.read();
}

void img_conv_5x5::thread_outptr_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        outptr_ce0 = ap_const_logic_1;
    } else {
        outptr_ce0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_outptr_d0() {
    outptr_d0 = (!icmp_reg_637.read()[0].is_01())? sc_lv<8>(): ((icmp_reg_637.read()[0].to_bool())? ap_const_lv8_FF: tmp_13_reg_642.read());
}

void img_conv_5x5::thread_outptr_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        outptr_we0 = ap_const_logic_1;
    } else {
        outptr_we0 = ap_const_logic_0;
    }
}

void img_conv_5x5::thread_p_cast_fu_516_p1() {
    p_cast_fu_516_p1 = esl_sext<21,19>(tmp_12_fu_510_p2.read());
}

void img_conv_5x5::thread_p_rec_fu_252_p2() {
    p_rec_fu_252_p2 = (!IN5_0_rec_reg_186.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(IN5_0_rec_reg_186.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void img_conv_5x5::thread_p_s_fu_358_p3() {
    p_s_fu_358_p3 = (!tmp_1_fu_350_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_1_fu_350_p3.read()[0].to_bool())? ap_const_lv21_0: tmp_fu_346_p1.read());
}

void img_conv_5x5::thread_sum00_fu_454_p0() {
    sum00_fu_454_p0 =  (sc_lv<8>) (sum00_fu_454_p00.read());
}

void img_conv_5x5::thread_sum00_fu_454_p00() {
    sum00_fu_454_p00 = esl_zext<16,8>(reg_221.read());
}

void img_conv_5x5::thread_sum00_fu_454_p1() {
    sum00_fu_454_p1 = reg_225.read();
}

void img_conv_5x5::thread_sum00_fu_454_p2() {
    sum00_fu_454_p2 = (!sum00_fu_454_p0.read().is_01() || !sum00_fu_454_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(sum00_fu_454_p0.read()) * sc_bigint<8>(sum00_fu_454_p1.read());
}

void img_conv_5x5::thread_sum1_cast_fu_293_p1() {
    sum1_cast_fu_293_p1 = esl_zext<64,6>(sum1_fu_287_p2.read());
}

void img_conv_5x5::thread_sum1_fu_287_p2() {
    sum1_fu_287_p2 = (!IN5_0_rec_reg_186.read().is_01() || !tmp_4_cast_fu_283_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(IN5_0_rec_reg_186.read()) + sc_biguint<6>(tmp_4_cast_fu_283_p1.read()));
}

void img_conv_5x5::thread_sum33_fu_478_p0() {
    sum33_fu_478_p0 =  (sc_lv<8>) (sum33_fu_478_p00.read());
}

void img_conv_5x5::thread_sum33_fu_478_p00() {
    sum33_fu_478_p00 = esl_zext<16,8>(inptr_q1.read());
}

void img_conv_5x5::thread_sum33_fu_478_p1() {
    sum33_fu_478_p1 = mask_q1.read();
}

void img_conv_5x5::thread_sum33_fu_478_p2() {
    sum33_fu_478_p2 = (!sum33_fu_478_p0.read().is_01() || !sum33_fu_478_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(sum33_fu_478_p0.read()) * sc_bigint<8>(sum33_fu_478_p1.read());
}

void img_conv_5x5::thread_sum3_cast_fu_386_p1() {
    sum3_cast_fu_386_p1 = esl_zext<64,7>(sum3_reg_616.read());
}

void img_conv_5x5::thread_sum3_fu_306_p2() {
    sum3_fu_306_p2 = (!tmp1_fu_298_p3.read().is_01() || !IN5_0_rec_cast17_cas_reg_573.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp1_fu_298_p3.read()) + sc_biguint<7>(IN5_0_rec_cast17_cas_reg_573.read()));
}

void img_conv_5x5::thread_sum5_cast_fu_390_p1() {
    sum5_cast_fu_390_p1 = esl_zext<64,8>(sum5_reg_622.read());
}

void img_conv_5x5::thread_sum5_fu_319_p2() {
    sum5_fu_319_p2 = (!tmp2_fu_311_p3.read().is_01() || !IN5_0_rec_cast2_reg_568.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp2_fu_311_p3.read()) + sc_biguint<8>(IN5_0_rec_cast2_reg_568.read()));
}

void img_conv_5x5::thread_sum7_cast1_fu_414_p1() {
    sum7_cast1_fu_414_p1 = esl_sext<8,7>(sum3_reg_616.read());
}

void img_conv_5x5::thread_sum7_cast_fu_417_p1() {
    sum7_cast_fu_417_p1 = esl_zext<64,8>(sum7_cast1_fu_414_p1.read());
}

void img_conv_5x5::thread_sum9_cast_fu_422_p1() {
    sum9_cast_fu_422_p1 = esl_zext<64,9>(sum9_reg_627.read());
}

void img_conv_5x5::thread_sum9_fu_332_p2() {
    sum9_fu_332_p2 = (!tmp4_fu_324_p3.read().is_01() || !IN5_0_rec_cast1_reg_563.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp4_fu_324_p3.read()) + sc_biguint<9>(IN5_0_rec_cast1_reg_563.read()));
}

void img_conv_5x5::thread_sum_1_fu_341_p2() {
    sum_1_fu_341_p2 = (!sum_cast_fu_337_p1.read().is_01() || !shift.read().is_01())? sc_lv<32>(): sc_bigint<32>(sum_cast_fu_337_p1.read()) >> (unsigned short)shift.read().to_uint();
}

void img_conv_5x5::thread_sum_2_fu_520_p2() {
    sum_2_fu_520_p2 = (!sum_reg_198.read().is_01() || !p_cast_fu_516_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(sum_reg_198.read()) + sc_bigint<21>(p_cast_fu_516_p1.read()));
}

void img_conv_5x5::thread_sum_cast_fu_337_p1() {
    sum_cast_fu_337_p1 = esl_sext<32,21>(sum_reg_198.read());
}

void img_conv_5x5::thread_tmp1_fu_298_p3() {
    tmp1_fu_298_p3 = esl_concat<4,3>(ap_const_lv4_8, i_reg_210.read());
}

void img_conv_5x5::thread_tmp2_fu_311_p3() {
    tmp2_fu_311_p3 = esl_concat<5,3>(ap_const_lv5_10, i_reg_210.read());
}

void img_conv_5x5::thread_tmp4_fu_324_p3() {
    tmp4_fu_324_p3 = esl_concat<6,3>(ap_const_lv6_20, i_reg_210.read());
}

void img_conv_5x5::thread_tmp7_cast_fu_504_p1() {
    tmp7_cast_fu_504_p1 = esl_sext<19,17>(tmp7_reg_712.read());
}

void img_conv_5x5::thread_tmp8_cast_fu_507_p1() {
    tmp8_cast_fu_507_p1 = esl_sext<19,18>(tmp8_reg_717.read());
}

void img_conv_5x5::thread_tmp_10_fu_436_p2() {
    tmp_10_fu_436_p2 = (!i_cast1_reg_591.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<5>(): (sc_biguint<5>(i_cast1_reg_591.read()) + sc_bigint<5>(ap_const_lv5_14));
}

void img_conv_5x5::thread_tmp_11_fu_441_p1() {
    tmp_11_fu_441_p1 = esl_zext<64,5>(tmp_10_fu_436_p2.read());
}

void img_conv_5x5::thread_tmp_12_fu_510_p2() {
    tmp_12_fu_510_p2 = (!tmp8_cast_fu_507_p1.read().is_01() || !tmp7_cast_fu_504_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(tmp8_cast_fu_507_p1.read()) + sc_bigint<19>(tmp7_cast_fu_504_p1.read()));
}

void img_conv_5x5::thread_tmp_13_fu_382_p1() {
    tmp_13_fu_382_p1 = p_s_fu_358_p3.read().range(8-1, 0);
}

void img_conv_5x5::thread_tmp_1_fu_350_p3() {
    tmp_1_fu_350_p3 = sum_1_fu_341_p2.read().range(20, 20);
}

void img_conv_5x5::thread_tmp_2_fu_366_p4() {
    tmp_2_fu_366_p4 = p_s_fu_358_p3.read().range(20, 8);
}

void img_conv_5x5::thread_tmp_4_cast_fu_283_p1() {
    tmp_4_cast_fu_283_p1 = esl_zext<6,3>(i_reg_210.read());
}

void img_conv_5x5::thread_tmp_4_fu_278_p1() {
    tmp_4_fu_278_p1 = esl_zext<64,3>(i_reg_210.read());
}

void img_conv_5x5::thread_tmp_5_fu_394_p2() {
    tmp_5_fu_394_p2 = (!i_cast_reg_597.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<4>(): (sc_biguint<4>(i_cast_reg_597.read()) + sc_biguint<4>(ap_const_lv4_5));
}

void img_conv_5x5::thread_tmp_6_fu_399_p1() {
    tmp_6_fu_399_p1 = esl_zext<64,4>(tmp_5_fu_394_p2.read());
}

void img_conv_5x5::thread_tmp_7_fu_404_p2() {
    tmp_7_fu_404_p2 = (!i_cast_reg_597.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<4>(): (sc_biguint<4>(i_cast_reg_597.read()) + sc_bigint<4>(ap_const_lv4_A));
}

void img_conv_5x5::thread_tmp_8_fu_409_p1() {
    tmp_8_fu_409_p1 = esl_zext<64,4>(tmp_7_fu_404_p2.read());
}

void img_conv_5x5::thread_tmp_9_fu_426_p2() {
    tmp_9_fu_426_p2 = (!i_cast1_reg_591.read().is_01() || !ap_const_lv5_F.is_01())? sc_lv<5>(): (sc_biguint<5>(i_cast1_reg_591.read()) + sc_biguint<5>(ap_const_lv5_F));
}

void img_conv_5x5::thread_tmp_fu_346_p1() {
    tmp_fu_346_p1 = sum_1_fu_341_p2.read().range(21-1, 0);
}

void img_conv_5x5::thread_tmp_s_fu_431_p1() {
    tmp_s_fu_431_p1 = esl_zext<64,5>(tmp_9_fu_426_p2.read());
}

void img_conv_5x5::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_246_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_266_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

void img_conv_5x5::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inptr_address0\" :  \"" << inptr_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inptr_ce0\" :  \"" << inptr_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inptr_q0\" :  \"" << inptr_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inptr_address1\" :  \"" << inptr_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inptr_ce1\" :  \"" << inptr_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inptr_q1\" :  \"" << inptr_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outptr_address0\" :  \"" << outptr_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outptr_ce0\" :  \"" << outptr_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outptr_we0\" :  \"" << outptr_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outptr_d0\" :  \"" << outptr_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mask_address0\" :  \"" << mask_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mask_ce0\" :  \"" << mask_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mask_q0\" :  \"" << mask_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mask_address1\" :  \"" << mask_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mask_ce1\" :  \"" << mask_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mask_q1\" :  \"" << mask_q1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"shift\" :  \"" << shift.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

